image: node:10

before_script:
  - yarn install
  - yarn run solc

test_funding:
  script:
  - env TZ='Asia/Taipei' node node_modules/.bin/mocha  --exit test_CI/apiTest.js
  after_script:
    when: on_failure
    - node test_CI/deleteSymbol.js