image: node:10

before_script:
  - yarn install
  - yarn run solc

test_funding:
  script:
  - env TZ='Asia/Taipei' node node_modules/.bin/mocha  --exit test_CI/apiTest.js
  - touch job_succeeded
  after_script:
  - if [ ! -f job_succeeded ] ;then node test_CI/deleteSymbol.js ;else exit 0;fi
  - rm job_succeeded

