```mermaid
graph TD
A[FMN上傳區] -->|上傳| B[FMS審核區]
B --> |審核|C{是否通過FMS審核}
C -->|否: 駁回修改| A
C -->|是: 提案| D[平台方待審核區]

D -->|審核| E{是否通過平台審核}
E -->|否: 駁回修改|B
E -->|是: 上架+部署CrowdFunding|F[募資區: 前端顯示]
F -->|進行募資|G{募資是否正常}

G -->|否|H[暫停區: 前端不顯示]
H -->I{是否能恢復募資}
I -->|是: 恢復募資|F
I -->|否: 終止募資,下架|J[緊急下架區: 人工判斷是否退款]
G -->|是|K{時間內是否達標}
K -->|否: 募資失敗|L[募資失敗區]
L -->|退款|M[已退款區]

K -->|是: 募資成功,部署TokenController + HCAT721|N[代幣待發放區]
N -->O{是否確認可發放}
O -->|否|J
O -->|是: 發放代幣|P[部署 IncomeManager]
P -->Q[執行 ProductManager, 將專案的4張合約的地址寫入並綁定]
Q -->R[營運管理區區]
R -->S{是否正常營運 發放租金}
S -->|是| S
S --> |否|S2[重新調整租金發放]
S2 --> |繼續運行|S
S -->|抵達有效日期|T{提案延長期限}
T -->|是|S
T -->|否|V[案件终止, 终止所有代幣權利和義務]

```

graph TD
A[新用戶註冊] -->|上傳照片/編輯個人資料| B[用戶審核區]
B --> |提交審核|C{是否通過管理者審核}
C -->|否: 駁回| B
C -->|是: 用戶升級| D[用戶活躍區&正常交易行為]
D --> |可疑的交易行為|C
